version: '3.9'

services:
  app:
    build:
      context: ./viajeros-del-eje-api
      dockerfile: docker/php/Dockerfile
    container_name: viajeros_del_eje_api
    volumes:
      - ./viajeros-del-eje-api:/var/www
    env_file:
      - ./viajeros-del-eje-api/.env
    depends_on:
      - postgres
    networks:
      - laravel

  postgres:
    image: postgres:16
    container_name: viajeros_del_eje_db
    restart: always
    ports:
      - "5435:5432" # host:container (acceso desde tu máquina)
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: viajeros_del_eje_nginx
    ports:
      - "8000:80"
    volumes:
      - ./viajeros-del-eje-api:/var/www
      - ./viajeros-del-eje-api/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  frontend:
    build:
      context: ./viajeros-del-eje-web
    container_name: viajeros_del_eje_web
    ports:
      - "3000:3000"
    env_file:
      - ./viajeros-del-eje-web/.env
    command: pnpm dev  # <-- modo desarrollo
    volumes:
      - ./viajeros-del-eje-web:/app  # sí para dev
    depends_on:
      - nginx
    networks:
      - laravel
networks:
  laravel:


volumes:
  pgdata:
